<%@ page session="false" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="petclinic" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
	
	$('#comboboxDates').change(function(){
		var valDate = $(this).val();
		$.ajax({
			type: 'GET',
			url: '${pageContext.request.contextPath}/restaurantreservations/' + valDate,
			success: function(result){
				var result = JSON.parse(result)
				var s1= '';
				for(var i = 0; i < result.length; i++){
					var num = result[i].id;
					var digits = num.toString().split('');
					var realDigits = digits.map(Number);
					if(realDigits.length==1){
						if(realDigits[0]==0){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="0"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="0"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==1){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="1"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="1"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==2){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="2"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="2"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==3){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="3"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="3"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==4){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="4"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="4"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==5){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="5"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="5"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==6){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="6"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="6"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==7){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="7"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="7"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==8){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="8"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="8"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}else if(realDigits[0]==9){
							s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="9"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="9"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
						}
					}else if(realDigits.length==2){
						if(realDigits[0]==1){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="10"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="10"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="11"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="11"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="12"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="12"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="13"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="13"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="14"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="14"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="15"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="15"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="16"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="16"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="17"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="17"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="18"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="18"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="19"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="19"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==2){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="20"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="20"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="21"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="21"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="22"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="22"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="23"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="23"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="24"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="24"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="25"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="25"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="26"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="26"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="27"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="27"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="28"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="28"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="29"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="29"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==3){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="30"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="30"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="31"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="31"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="32"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="32"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="33"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="33"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="34"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="34"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="35"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="35"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="36"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="36"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="37"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="37"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="38"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="38"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="39"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="39"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==4){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="40"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="40"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="41"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="41"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="42"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="42"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="43"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="43"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="44"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="44"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="45"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="45"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="46"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="46"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="47"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="47"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="48"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="48"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="49"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="49"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==5){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="50"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="50"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="51"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="51"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="52"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="52"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="53"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="53"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="54"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="54"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="55"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="55"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="56"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="56"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="57"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="57"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="58"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="58"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="59"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="59"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==6){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="60"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="60"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="61"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="61"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="62"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="62"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="63"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="63"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="64"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="64"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="65"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="65"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="66"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="66"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="67"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="67"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="68"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="68"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="69"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="69"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==7){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="70"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="70"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="71"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="71"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="72"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="72"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="73"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="73"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="74"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="74"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="75"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="75"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="76"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="76"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="77"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="77"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="78"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="78"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="79"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="79"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==8){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="80"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="80"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="81"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="81"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="82"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="82"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="83"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="83"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="84"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="84"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="85"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="85"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="86"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="86"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="87"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="87"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="88"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="88"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="89"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="89"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}else if(realDigits[0]==9){
							if(realDigits[1]==0){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="90"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="90"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==1){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="91"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="91"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==2){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="92"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="92"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==3){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="93"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="93"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==4){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="94"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="94"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==5){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="95"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="95"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==6){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="96"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="96"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==7){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="97"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="97"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==8){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="98"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="98"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}else if(realDigits[1]==9){
								s1 += '<tr> <td> ' + result[i].restaurant_table.id + ' </td>' + '<td>' + result[i].client.name + '</td>' + '<td>' + result[i].time_interval.name + '</td>' + '<td> <spring:url value="/restaurantreservations/delete/{restaurantreservationId}" var="restaurantreservationUrl">' + '<spring:param name="restaurantreservationId" value="99"/> </spring:url> <a href="${fn:escapeXml(restaurantreservationUrl)}">Delete</a> </td> ' + '<td> <spring:url value="/restaurantreservations/{restaurantreservationId}/edit" var="editUrl"> ' + '<spring:param name="restaurantreservationId" value="99"/> </spring:url> <a href="${fn:escapeXml(editUrl)}">Update</a> </td> </tr>';
							}
						}
					}
				}
				$('#reservations').html(s1);
			}
		});
	});
});
</script>

<petclinic:layout pageName="restaurantreservations">
    <h2>Restaurant Reservations</h2>
    
    <div class="control-group">
    	Dates <select id="comboboxDates" name="date">
        	<option selected>Selecciona fecha</option>
        	<c:forEach var="date" items="${dates}">
            	<option value="${date}">${date}</option>
        	</c:forEach>
        </select>
    </div>

    <table id="restaurantReservationsTable" class="table table-striped">
        <thead>
        <tr>
        	<th style="width: 200px;">Table</th>
            <th style="width: 200px;">Client</th>
            <th style="width: 200px;">Interval</th>
            <th>Actions</th>
            <th></th>
        </tr>
        </thead>
        <tbody id="reservations"></tbody>
    </table>    
</petclinic:layout>